name: React demo tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Go to the app directory
        run: cd react-demo

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
