name: Deploy project

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./react-demo
        run: |
          npm ci

      - name: Run tests
        working-directory: ./react-demo
        run: npm test

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./react-demo
        run: |
          npm ci

      - name: Build
        working-directory: ./react-demo
        run: npm run build

      - name: Deploy
        run: echo "Deploying!"